
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 18 02:11:14 CET 2023
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.Scanner;
import java.io.*;
import java.util.*;
import SymbolTable.*;

/** CUP v0.10k generated parser.
  * @version Mon Dec 18 02:11:14 CET 2023
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\030\000\002\003\005\000\002\002\004\000\002\004" +
    "\004\000\002\005\004\000\002\005\003\000\002\006\005" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\007\005\000\002\007\003\000\002\010\003\000\002" +
    "\010\003\000\002\015\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\003\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\013\003\000\002\014\012\000" +
    "\002\016\005\000\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\054\000\004\004\005\001\002\000\004\002\056\001" +
    "\002\000\010\006\014\007\013\010\012\001\002\000\014" +
    "\006\ufffd\007\ufffd\010\ufffd\011\ufffd\023\ufffd\001\002\000" +
    "\004\023\054\001\002\000\004\005\053\001\002\000\014" +
    "\006\014\007\013\010\012\011\016\023\021\001\002\000" +
    "\004\023\ufff9\001\002\000\004\023\ufffa\001\002\000\004" +
    "\023\ufffb\001\002\000\006\005\ufff6\017\ufff6\001\002\000" +
    "\004\023\041\001\002\000\014\006\ufffe\007\ufffe\010\ufffe" +
    "\011\ufffe\023\ufffe\001\002\000\006\005\ufff7\017\ufff7\001" +
    "\002\000\004\016\026\001\002\000\006\005\uffff\017\024" +
    "\001\002\000\006\005\ufff5\017\ufff5\001\002\000\006\011" +
    "\016\023\021\001\002\000\006\005\ufff8\017\ufff8\001\002" +
    "\000\012\023\030\024\027\025\031\026\034\001\002\000" +
    "\012\005\ufff0\014\ufff0\015\ufff0\017\ufff0\001\002\000\012" +
    "\005\uffed\014\uffed\015\uffed\017\uffed\001\002\000\012\005" +
    "\uffee\014\uffee\015\uffee\017\uffee\001\002\000\012\005\ufff1" +
    "\014\ufff1\015\ufff1\017\ufff1\001\002\000\012\005\ufff4\014" +
    "\035\015\036\017\ufff4\001\002\000\012\005\uffef\014\uffef" +
    "\015\uffef\017\uffef\001\002\000\012\023\030\024\027\025" +
    "\031\026\034\001\002\000\012\023\030\024\027\025\031" +
    "\026\034\001\002\000\012\005\ufff2\014\ufff2\015\ufff2\017" +
    "\ufff2\001\002\000\012\005\ufff3\014\ufff3\015\ufff3\017\ufff3" +
    "\001\002\000\004\012\042\001\002\000\004\021\043\001" +
    "\002\000\004\023\044\001\002\000\006\020\uffea\022\uffea" +
    "\001\002\000\006\020\046\022\047\001\002\000\004\023" +
    "\052\001\002\000\004\013\050\001\002\000\006\011\016" +
    "\023\021\001\002\000\006\005\uffec\017\uffec\001\002\000" +
    "\006\020\uffeb\022\uffeb\001\002\000\004\002\001\001\002" +
    "\000\004\017\055\001\002\000\014\006\ufffc\007\ufffc\010" +
    "\ufffc\011\ufffc\023\ufffc\001\002\000\004\002\000\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\054\000\004\003\003\001\001\000\002\001\001\000" +
    "\012\004\007\005\010\006\005\011\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\006" +
    "\016\007\021\010\017\011\006\014\022\015\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\010\024\014\022\015\014\001\001\000\002" +
    "\001\001\000\006\012\032\013\031\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\037\001" +
    "\001\000\004\013\036\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\010\050\014\022\015" +
    "\014\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

 	symbolTable = new SymbolTable();

    }


	SymbolTable symbolTable;
	public int warnNo = 0;
	public int errNo = 0;
	
   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new MPLexer( file );
		   MPParser parser = new MPParser( scanner );
		   parser.parse();
		   parser.checkWarnings();
		   if ( parser.warnNo==0 && parser.errNo == 0)
				 System.out.println(
				"Analiza zavrsena. U kodu nema gresaka." );
			 else{
				 System.out.println(
				 "Analiza zavrsena. Broj upozorenja: " +
				 parser.warnNo );
				 
				 System.out.println("Broj gresaka: " + parser.errNo);
			 }
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }
   
   public int getLine()
   {
   		return ((MPLexer) getScanner()).getLine();
   }
   
   public void checkWarnings()
 	{
		 SymbolNode current = symbolTable.getVariables();
		 while ( current != null )
		 {
			 Variable var = ( Variable ) current;
			 if ( var.last_def == -1 && var.last_use == -1 )
			 {
				 System.out.println("Upozorenje: Promenljiva "
				+ var.name +
				"je deklarisana, ali se ne koristi.");
				 warnNo++;
			 }
			 else if ( var.last_def > var.last_use )
			 {
				 System.out.println(
				 "Upozorenje: Vrednost dodeljena prom. "
				+ var.name + " u liniji " + var.last_def +
				" se nigde ne koristi." );
				 warnNo++;
			 }
			 current = current.next;
		}
 }  

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NameList ::= ID 
            {
              ArrayList RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
           	  RESULT = new ArrayList();
           	  RESULT.add(ime);
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NameList ::= NameList COMMA ID 
            {
              ArrayList RESULT = null;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
              RESULT = niz;
              RESULT.add(ime);
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ApplyExpression ::= FOR ID IN OPEN_SQUARE_BRACKET NameList CLOSED_SQUARE_BRACKET APPLY Expression 
            {
              Type RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).value;
		int nizleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int nizright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		ArrayList niz = (ArrayList)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		
          	int t;
          	if(niz.size() > 0){
          		ime = (String)niz.get(0);
          		t = parser.symbolTable.getVar(ime).type.tkind;
          	
	          	boolean nizPromenljivihBad = false;
	          	boolean promenljivaBad = false;
	          	
	             for(int i = 0 ; i < niz.size(); i++){
	              	String imeUNizu = (String) niz.get(i);
	              	
	              	Variable var = parser.symbolTable.getVar(ime);
	              	Variable varNiz = parser.symbolTable.getVar(imeUNizu);
	              	
	              	if( var == null ){
	              		System.out.println("Greska, promenjiva " +ime+ "nije deklarisana.");
	              		parser.errNo++;
	              	}else if(varNiz.type.tkind != var.type.tkind){
	              		System.out.println("Tip promenjive" + ime + " se ne slaze sa tipom promenjivih iz niza NameList");
	              		promenljivaBad = true;
	              	}else if(varNiz.type.tkind != t){
	              		System.out.println("Tipovi promenjivih u NameList-i " + niz + " nisu homogeni");
	              		nizPromenljivihBad = true;
	              	}	
	              }
	              
	              if(nizPromenljivihBad || promenljivaBad){
	              	RESULT = parser.symbolTable.getType("unknown");
	              	parser.errNo++;
	              }else{
	              	if(t == Type.INTEGER){
	              		RESULT = parser.symbolTable.getType("integer");
	              	}else if(t == Type.FLOAT){
	              		RESULT = parser.symbolTable.getType("float");
	              	}else if(t == Type.BOOLEAN){
	              		RESULT = parser.symbolTable.getType("boolean");
	              	}else{
	              		RESULT = parser.symbolTable.getType("unknown");
	              	}
	              }
              }
          
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // TermExpression ::= ID 
            {
              Type RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
         		Variable var = parser.symbolTable.getVar(ime);
         		if(var == null){
         			System.out.println( "Ggreska u liniji " +
						parser.getLine() +
						 ": promenljiva " + ime +
						" nije deklarisana.");
					RESULT = parser.symbolTable.getType("unknown");
					parser.errNo++;
         		}else
         		{
         			RESULT = var.type;
         			if(var.last_def == -1){
         				System.out.println("Greska u liniji "
							 + parser.getLine() +
							 ": promenljiva " + ime + " nije inicijalizovana."); 
         				parser.errNo++;
         			}
         			var.last_use = parser.getLine();
         		}
         	
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // TermExpression ::= BOOLEANCONST 
            {
              Type RESULT = null;
		
         		RESULT = parser.symbolTable.getType("boolean");
         	
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // TermExpression ::= FLOATCONST 
            {
              Type RESULT = null;
		
         		RESULT = parser.symbolTable.getType("float");
         	
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // TermExpression ::= INTCONST 
            {
              Type RESULT = null;
		
            	RESULT = parser.symbolTable.getType("integer");
         	
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ArithmeticExpression ::= TermExpression 
            {
              Type RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
          		if (i.tkind == Type.INTEGER){
          			RESULT = parser.symbolTable.getType("integer");
          		}else if(i.tkind == Type.FLOAT){
          			RESULT = parser.symbolTable.getType("float");
          		}else {
          			System.out.println("Greska prilikom dodele, linija: " + parser.getLine());
          			parser.errNo++;
          			RESULT = parser.symbolTable.getType("unknown");
          		}
          	
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ArithmeticExpression ::= ArithmeticExpression MINUS TermExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
              if( i1.tkind == Type.INTEGER && i2.tkind == Type.INTEGER){
              		RESULT = parser.symbolTable.getType("integer");
              	}else if(i1.tkind == Type.FLOAT && (i2.tkind == Type.FLOAT || i2.tkind == Type.INTEGER)){
              		RESULT = parser.symbolTable.getType("float");
              	}else if(i2.tkind == Type.FLOAT && (i1.tkind == Type.FLOAT || i1.tkind == Type.INTEGER)){
              		RESULT = parser.symbolTable.getType("float");
              	}else{
              		System.out.println("Nije moguce oduzeti operande zbog neslaganja tipova u liniji: " + parser.getLine());
              		RESULT = parser.symbolTable.getType("unknown");
              		parser.errNo++;
              	}
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ArithmeticExpression ::= ArithmeticExpression PLUS TermExpression 
            {
              Type RESULT = null;
		int i1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type i1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
              	if( i1.tkind == Type.INTEGER && i2.tkind == Type.INTEGER){
              		RESULT = parser.symbolTable.getType("integer");
              	}else if(i1.tkind == Type.FLOAT && (i2.tkind == Type.FLOAT || i2.tkind == Type.INTEGER)){
              		RESULT = parser.symbolTable.getType("float");
              	}else if(i2.tkind == Type.FLOAT && (i1.tkind == Type.FLOAT || i1.tkind == Type.INTEGER)){
              		RESULT = parser.symbolTable.getType("float");
              	}else{
              		System.out.println("Nije moguce sabrati operande zbog neslaganja tipova u liniji: " + parser.getLine());
              		RESULT = parser.symbolTable.getType("unknown");
              		parser.errNo++;
              	}
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Assignment ::= ID ASSIGN ArithmeticExpression 
            {
              Type RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type i = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
              Variable var = parser.symbolTable.getVar(ime);
              
              if(var == null){
              	RESULT = parser.symbolTable.getType("unknown");
              	System.out.println("Unknown type in line: " + parser.getLine());
              	parser.errNo++;
              }else{           
	              int t = var.type.tkind;
	              
	              if(t == i.tkind){
	              	if(i.tkind == Type.INTEGER){
	              		RESULT = parser.symbolTable.getType("integer");
	              		var.last_def = parser.getLine();
	              	}else if(i.tkind == Type.FLOAT){
	              		RESULT = parser.symbolTable.getType("float");
	              		var.last_def = parser.getLine();
	              		
	              	}else if(i.tkind == Type.BOOLEAN){
	              		RESULT = parser.symbolTable.getType("boolean");
	              		var.last_def = parser.getLine();
	              	}else{
	              		RESULT = parser.symbolTable.getType("unknown");
	              		System.out.println("Unknown type in line: " + parser.getLine());
	              		parser.errNo++;
	              	}	
	              }else{
	              	if(t == Type.FLOAT && i.tkind == Type.INTEGER){
	              		RESULT = parser.symbolTable.getType("float");
	              		var.last_def = parser.getLine();
	              	}else{
	              		RESULT = parser.symbolTable.getType("unknown");
	              		System.out.println("Types missmatch in line: " + parser.getLine());
	              		parser.errNo++;
	              	}
	              }
              }
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Expression ::= ApplyExpression 
            {
              Object RESULT = null;
		
       		System.out.println("Redukcija 11: Expression ::= ApplyExpression" );  
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Expression ::= Assignment 
            {
              Object RESULT = null;
		
            System.out.println( "Redukcija 10: Expression ::= Assignment" );
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Expressions ::= Expression 
            {
              Object RESULT = null;
		
           System.out.println( "Redukcija 9: Expressions ::= Expression" );
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Expressions*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Expressions ::= Expressions SEMICOLON Expression 
            {
              Object RESULT = null;
		
           System.out.println( "Redukcija 8: Expressions ::= Expressions SEMICOLON EXPRESSION" );
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Expressions*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Tip ::= BOOL 
            {
              Type RESULT = null;
		
           	 	RESULT = parser.symbolTable.getType("boolean");
           	 
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Tip ::= FLOAT 
            {
              Type RESULT = null;
		
				RESULT = parser.symbolTable.getType("float");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Tip ::= INT 
            {
              Type RESULT = null;
		
                RESULT = parser.symbolTable.getType("integer");
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Tip*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declaration ::= Tip ID SEMICOLON 
            {
              Object RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                if(!parser.symbolTable.addVar(id,t)){
                	System.out.println("Promenjiva " + id + " je vec deklarisana.");
                	parser.errNo++;
                }
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Declarations ::= Declaration 
            {
              Object RESULT = null;
		
                System.out.println( "Redukcija 4: Declarations ::= Declaration" );
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Declarations ::= Declarations Declaration 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija 3: Declarations ::= Declarations Declaration" );
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Block ::= Declarations Expressions 
            {
              Object RESULT = null;
		
                System.out.println( "Redukcija 2: Block ::= Declarations Expressions" );
             
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN Block EXIT 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija 1: Program ::= main Block exit" );
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

