
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 18 01:51:54 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 3;
  public static final int SEMICOLON = 13;
  public static final int PLUS = 10;
  public static final int INT = 4;
  public static final int IN = 8;
  public static final int OPEN_SQUARE_BRACKET = 15;
  public static final int BOOLEANCONST = 19;
  public static final int APPLY = 9;
  public static final int INTCONST = 18;
  public static final int ID = 17;
  public static final int COMMA = 14;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int CLOSED_SQUARE_BRACKET = 16;
  public static final int ASSIGN = 12;
  public static final int BOOL = 6;
  public static final int FLOATCONST = 20;
  public static final int FOR = 7;
}

